name: flutter_sliding_tutorial
description: Applied parallax effects will make your product presentation look like Google apps tutorial.
version: 0.1.0
author: "cleveroad.com <info@cleveroad.com>"
homepage: https://github.com/Cleveroad/flutter_sliding_tutorial

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
